server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
#          uri: file:///E:/workspace/spring-cloud/
          uri: https://github.com/AllenAi007/spring-cloud.git
          basedir: config

---
spring:
  profiles: dev